### ISSUE TITLE
IndexOutOfBoundsException

### ISSUE THREAD

**Issue by TheKeyOfficial** [DomenicDev/Bomberman#41]
Exception in thread "Thread-0" java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at de.fuwa.bomberman.game.appstates.Ki.Path.getMove(Path.java:24)
	at de.fuwa.bomberman.game.appstates.Ki.KiAppstate.update(KiAppstate.java:97)
	at de.fuwa.bomberman.app.GameApplication$GameLoop.run(GameApplication.java:127)
	at java.lang.Thread.run(Thread.java:748)

**Comment by DomenicDev** [comment]
This issue seems to be fixed with version 1.0
