### ISSUE TITLE
Null pointer when two players die from one explosion

### ISSUE THREAD

**Issue by DomenicDev** [DomenicDev/Bomberman#42]
When the score is told to increase it searches for the Score Component of the specific player. But if two (may be the last two alive) players die due to the same explosion both players aren't there anymore but it is still tried to increase the score component which is not there anymore once the player is totally removed.

Here is the strack trace:

```
Exception in thread "Thread-0" java.lang.NullPointerException
	at de.fuwa.bomberman.game.appstates.ExplosionAppState.update(ExplosionAppState.java:49)
	at de.fuwa.bomberman.app.GameApplication$GameLoop.run(GameApplication.java:127)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by DomenicDev** [comment]
We can close this since we are not going to improve the code in KIAppState in the next time.
