### ISSUE TITLE
invalid stream header

### ISSUE THREAD

**Issue by TheKeyOfficial** [DomenicDev/Bomberman#44]
java.io.StreamCorruptedException: invalid stream header: 54686520
	at java.io.ObjectInputStream.readStreamHeader(ObjectInputStream.java:857)
	at java.io.ObjectInputStream.<init>(ObjectInputStream.java:349)
	at de.fuwa.bomberman.game.utils.ExternalDataManager.readCustomMap(ExternalDataManager.java:24)
	at de.fuwa.bomberman.game.utils.ExternalDataManager.readAllCustomMaps(ExternalDataManager.java:41)
	at de.fuwa.bomberman.game.gui.SingleplayerMenu.addComponents(SingleplayerMenu.java:40)
	at de.fuwa.bomberman.game.gui.BasicFuwaManPanel.<init>(BasicFuwaManPanel.java:61)
	at de.fuwa.bomberman.game.gui.SingleplayerMenu.<init>(SingleplayerMenu.java:10)
	at de.fuwa.bomberman.game.appstates.FuwaManGuiHolderAppState.<init>(FuwaManGuiHolderAppState.java:23)
	at de.fuwa.bomberman.game.appstates.FuwaManAppState.initialize(FuwaManAppState.java:37)
	at de.fuwa.bomberman.app.AppStateManager.addStates(AppStateManager.java:44)
	at de.fuwa.bomberman.app.GameApplication$GameLoop.run(GameApplication.java:128)
	at java.lang.Thread.run(Thread.java:748)

**Comment by DomenicDev** [comment]
This exception is thrown because I recently added a info text file in the usermaps folder. This text file is tried to be interpreted into a GameField object I think which would lead to the exception you posted above.
